In [1]:
import numpy as np

In [10]:
a = np.array([[3, 3], [4, 3], [1, 1]], dtype='float32')
b = np.array([[1, 2], [3, 4]])
a@b

array([[ 12.,  18.],
       [ 13.,  20.],
       [  4.,   6.]])

In [9]:
(b[1].T)@b

array([15, 22])

In [18]:
a[1] @ a.T

array([ 21.,  25.,   7.], dtype=float32)

In [17]:
a[1].shape

(2,)

In [19]:
np.diag(a[0])

array([[ 3.,  0.],
       [ 0.,  3.]], dtype=float32)

In [23]:
tran_data = np.array([[3, 3], [4, 3], [1, 1]], dtype='float32')
tran_label = np.array([1, 1, -1], dtype='float32')

In [24]:
tran_label >= 0

array([ True,  True, False], dtype=bool)

In [26]:
tran_data[tran_label >= 0]

array([[ 3.,  3.],
       [ 4.,  3.]], dtype=float32)